<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>ds</string>
	</array>
	<key>name</key>
	<string>Demandware Script</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>source.js</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(importPackage|importScript|trace)</string>
			<key>name</key>
			<string>support.function.dwscript</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(PipelineDictionary|\sFile(?:\s|[^\w]))</string>
			<key>name</key>
			<string>support.type.dwscript</string>
		</dict>
		<dict>
			<key>match</key>
			<string>PIPELET_(ERROR|NEXT)</string>
			<key>name</key>
			<string>support.constant.dwscript</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#dwscript-type</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>dwscript-type</key>
		<dict>
			<key>begin</key>
			<string>(:\s*?)?((?:dw\.){1}(?:campaign|catalog|content|crypto|customer|io|net|object|oms|order|rpc|system|util|value|web)(?:\s|\.)?([A-Z]{1}[a-zA-Z0-9-_]+)?)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.namespace.dwscript</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>support.class.dwscript</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?:|\s|\.|,)</string>
			<key>endCaptures</key>
			<dict>
			</dict>
			<key>name</key>
			<string>support.class.dwscript</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.dwscript</string>
	<key>uuid</key>
	<string>253fe05e-a2cc-44e1-be30-c214c9ed4c13</string>
</dict>
</plist>
